name: CI/CD for Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: ~/.cache/docker
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t zasulanb/my-first-site:${{ github.sha }} .
        docker push zasulanb/my-first-site:${{ github.sha }}

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig
      run: |
        doctl kubernetes cluster kubeconfig save do-sfo3-k8s-1-31-1-do-4-sfo3-1731846316192

    - name: Update deployment image
      run: |
        kubectl set image deployment/hello-world hello-world=zasulanb/my-first-site:${{ github.sha }}
        kubectl rollout status deployment/hello-world