name: CI/CD for Kubernetes

on:
  push:
    branches:
      - main   # Слушаем изменения в ветке main, можно заменить на вашу рабочую ветку

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: ~/.cache/docker
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t zasulanb/my-first-site .
        docker push zasulanb/my-first-site

    # - name: Test kubectl connection
    #   run: kubectl cluster-info
      
    # - name: Create .kube directory
    #   run: mkdir -p ~/.kube

    # - name: Add kubeconfig
    #   run: echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
      
    # - name: Set up kubeconfig
    #   run: |
    #     echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config
    #     chmod 600 ~/.kube/config

    - name: Create kubeconfig directory
      run: mkdir -p ~/.kube

    - name: Set kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Apply Kubernetes manifest
      run: kubectl apply -f deployment.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl rollout restart deployment hello-world-deployment
